myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'myapp'

urlpatterns=[
   
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    
    path('login/', views.LoginView.as_view(), name='login'),
    path('details', views.DetailsView.as_view(), name='details'),
    path('job_status', views.JobStatusView.as_view(), name='job_status'),
    path('job_details', views.JobDetailsView.as_view(), name='job_details'),
    path('job_title', views.JobTitleView.as_view(), name='job_title'),
    path('relationship', views.RelationView.as_view(), name='relationship'),
    path('interested', views.InterestView.as_view(), name='interest'),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='myapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', views.ChangePasswordView.as_view(), name='password_change'),
    # path('reset_password/',auth_views.PasswordResetView.as_view(), name='reset_password'),
    # path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(), name='password_reset_done'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from myapp.views import ResetPasswordView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls',namespace='myapp')),
   
]
urlpatterns+=static(settings.STATIC_URL)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import random
import string
from datetime import timedelta
from django.utils import timezone

# Create your models here.
class User(AbstractUser):
    
    phone_number = models.CharField(max_length=10, unique=True,blank=True, null=True)
    # otp = models.CharField(max_length=6, blank=True, null=True)
    # otp_created_at = models.DateTimeField(blank=True, null=True)
    # otp = models.CharField(max_length=6)


    # def generate_otp(self):
    #     self.otp_code = ''.join(random.choices(string.digits, k=6))
    #     self.save()

    # def is_valid(self):
    #     # Add logic for OTP validity duration, e.g., 5 minutes
    #     return not self.is_used and self.created_at + timedelta(minutes=5) > timezone.now()

myapp/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.password_validation import validate_password

class UserCreationForm(forms.ModelForm):
    confirm_password = forms.CharField(
        max_length=25,
        min_length=8,
        widget=forms.PasswordInput({'class':'form-control'}))
    
    password = forms.CharField(
        max_length=25,
        min_length=8,
        widget=forms.PasswordInput({'class':'form-control'})
    
    )
    def clean_password(self):
        password = self.cleaned_data.get('password')
        
        # Validate the password using Django's built-in validators
        try:
            validate_password(password)
        except ValidationError as e:
            raise ValidationError(e)

        return password

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        # Check if the passwords match
        if password and confirm_password and password != confirm_password:
            raise ValidationError("Passwords do not match.")
        
        return confirm_password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


    phone_number = forms.CharField(
        max_length=10,
        required=True,
        validators=[RegexValidator(r'^\+?1?\d{9,15}$', 'Enter a valid phone number (up to 10 digits)')]
    )

    email = forms.EmailField(
        max_length=254, 
        required=True,
        widget=forms.EmailInput({'class':'form-control'})
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email.endswith('@gmail.com'):
            raise forms.ValidationError('Email must be from gmail.com domain.')
        return email
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_number', 'password']



    # otp = forms.CharField(
    #     max_length=6,
    #     widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter OTP'})
    # )    

class EmailOrMobileAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Email or Mobile', max_length=254,  widget=forms.TextInput({'class':'form-control'}))
    password = forms.CharField(
        max_length=25,
        min_length=8,
        widget=forms.PasswordInput({'class':'form-control'})
    
    )
# class OTPForm(forms.ModelForm):
#     otp = forms.CharField(max_length=6, required=True, label="OTP")

myapp/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView,FormView,TemplateView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as AuthLoginView
from myapp.forms import EmailOrMobileAuthenticationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .forms import *
from django.contrib import messages
from .models import User
from django.core.mail import send_mail
from django.contrib.auth.views import PasswordResetView,PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin




# Create your views here.


class HomeView(TemplateView):
    template_name = 'myapp/home.html'

class SignupView(FormView):
    model=User
    template_name= 'myapp/signup.html'
    form_class = UserCreationForm
    success_url=reverse_lazy('myapp:details')

    def form_valid(self, form):
    # Validate and clean passwords using the form's validation methods
        password = form.cleaned_data.get('password')
        confirm_password = form.cleaned_data.get('confirm_password')

    # Check if passwords match
        if password and confirm_password and password != confirm_password:
            form.add_error('confirm_password', "Passwords do not match.")
            return self.form_invalid(form)

    # Save the user instance, but don't commit to the database yet
        user = form.save(commit=False)

    # Set the password using set_password to ensure it is hashed
        user.set_password(password)
        user.save()  # Now save the user to the database

    # Specify the custom authentication backend
        backend = 'myapp.backends.EmailOrMobileBackend'
    
    # Log the user in using the custom backend
        login(self.request, user, backend=backend)
    
    # Redirect to the success URL
        return redirect(self.success_url)

class LoginView(AuthLoginView):
    template_name = 'myapp/login.html'
    form_class = EmailOrMobileAuthenticationForm
    success_url = reverse_lazy('myapp:details')

    def form_valid(self, form):
        user = form.get_user()
        backend = 'myapp.backends.EmailOrMobileBackend'
        login(self.request, user, backend=backend)
        return redirect(self.success_url)



class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'myapp/password_reset.html'
    email_template_name = 'myapp/password_reset_email.html'
    subject_template_name = 'myapp/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('myapp:home')


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'myapp/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('myapp:home')

class DetailsView(TemplateView):
    template_name = 'myapp/details.html'
    success_url = reverse_lazy('myapp:job_status')

class JobStatusView(TemplateView):
    template_name = 'myapp/job_status.html'


class JobDetailsView(TemplateView):
    template_name = 'myapp/job_details.html'




class JobTitleView(TemplateView):
    template_name = 'myapp/job_title.html'


class RelationView(TemplateView):
    template_name = 'myapp/relationship_goals.html'


class InterestView(TemplateView):
    template_name = 'myapp/interested.html'

myapp/templates/myapp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<style>
    body {
        font-family: "Play", sans-serif;
        font-style: normal;
    }

     .container {
        height: 100%;
        width: 330px; 
        line-height: normal;
    }
</style>

<body>
    <div class="container">
        <form>
            <img class="profile" src="{% static 'images/profile.png' %}" height="300px" width="300px" style="right: 10px;"><br>
            <h2 class="head2">
                <center>Let meeting new people around you</center><br>
            </h2>
            <a href="{% url 'myapp:login' %}"type="submit" class="btn btn-dark custom-white-btn1 btn-block">
                <img src="{% static 'images/icons8-phone-100.png' %}" alt="call" height="30px" width="40px" class="call">
                Login with Email/Phone</a><br>
            <button type="button" class="btn btn-dark custom-white-btn btn-block">
                <img src="{% static 'images/google.svg' %}" alt="Google" height="20px" width="20px" class="google"> Login with Google
            </button>
            <center><p class="footer">Don't have an account? <a href="{% url 'myapp:signup' %}" class="link">Sign up</a></p></center>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>

myapp/templates/myapp/job_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Job Status Checkout</title>
<!--    {% load static %}-->
<!--        <link rel="stylesheet" href="static/css/details.css">-->
    <style>
body {
    background-image: url("{% static 'images/backgroundimg.png' %}");
    background-position: center -60%;
            background-size: auto;
            background-repeat: no-repeat;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        .container {
            background-color: white;
            max-width: 400px;
            width: 260px;
            margin: auto;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .heading {
            font-size: 26px;
            text-align: center;
            left:10px;
            margin-bottom: 20px;
        }
          .personal-details-form {
    display: flex;
    flex-direction: column;
}

.personal-details-form label {
    margin: 10px 0 5px;
    font-weight: bold;
}

.personal-details-form input {
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 4px;
}
        .link-button {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    width:220px;
    text-align: center;
    color: #fff;
    background-color: black; /* Button background color */
    text-decoration: none; /* Remove underline from link */
    border-radius: 5px; /* Rounded corners */
    border: 1px solid #007bff; /* Border matching the background */
    transition: background-color 0.3s, color 0.3s; /* Smooth transition */
}

.link-button:hover {
    background-color: #0056b3; /* Darker background on hover */
    color: #e6e6e6; /* Change text color on hover */
}
    </style>
</head>
<body>
    <div class="container">
        <div class="heading"><b>Job Details</b></div><br>
<form class="personal-details-form" method="post">
            <label for="Company Name"></label>
            <input  id="Company Name" name="Company Name" placeholder="Company Name">

           <label for="Designation"></label>
           <input  id="Designation" name="Designation" placeholder="Designation">

          <label for="Location"></label>
          <input id="Location" name="Location"  placeholder="Location"><br><br>
          <a href="{% url 'myapp:job_title' %}" class="link-button">Next</a>
</form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/myapp/job_status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job Status Checkout</title>
    {% load static %}
        <link rel="stylesheet" href="static/css/option.css">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body{
        background-image: url("{% static 'images/backgroundimg.png' %}");
        background-position: center -60%;
    background-size: auto;
    background-repeat: no-repeat;
    }
    .container{
        position: center;
        top: 80px; 
        width: 250px;
        right: 525px;
        
    }

    </style>
</head>
<body>
<div class="bg-image">
    <div class="container">
        <div class="heading"><b>Job Status</b></div><br>
        <div class="form-check">
             <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
             <label class="form-check-label" for="flexCheckDefault">Employee</label>
        </div>
        <div class="form-check">
             <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
             <label class="form-check-label" for="flexCheckChecked">Employer</label>
        </div>
        <div class="form-check">
             <input class="form-check-input" type="checkbox" value=""  checked>
             <label class="form-check-label" for="flexCheckChecked">Job Seeker</label>
        </div>
           <a href="{% url 'myapp:job_details' %}" class="link-button">Next</a>
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/myapp/job_title.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dating App</title>
<!--{% load static %}-->
<!--        <link rel="stylesheet" href="static/css/title.css">-->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f4f4f4;
        }


        .bg-image {
            background-image: url("{% static 'images/backgroundimg.png' %}");
    background-position: center -60%;
            background-size: auto;
            background-repeat: no-repeat;
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            position: absolute;
            width: 325px;
            z-index: -1;
        }

        .form-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 500px;
            height:445px;
            width: 325px;
             position: fixed;
            top: 90px; /* 10px from the bottom of the viewport */
            right: 520px;
        }

        .form-control {
            background-color: #fff;
            padding: 10px;
            margin-top:30px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 390px;
            width: 290px;

        }

        h2 {
            margin-bottom: 20px;
            font-size: 24px;
            text-align: center;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }


        select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            margin-top:40px;
            border-radius: 4px;
        }

        .link-button {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    width:290px;
    text-align: center;
    color: #fff;
    background-color: black; /* Button background color */
    text-decoration: none; /* Remove underline from link */
    border-radius: 5px; /* Rounded corners */
    border: 1px solid #007bff; /* Border matching the background */
    transition: background-color 0.3s, color 0.3s; /* Smooth transition */
}

.link-button:hover {
    background-color: #0056b3; /* Darker background on hover */
    color: #e6e6e6; /* Change text color on hover */
}




    </style>
</head>
<body>
 <div class="bg-image"></div>
      <div class="form-container">
        <h2>Job Details</h2>
        <form action="next_page.html" method="post">
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Title" aria-label="Title"><br><br>
                <label for="jobType">Expertise Level</label>
                <select id="jobType" name="jobType" required>
                    <option value="">Value</option>
                    <option value="value1">Beginner</option>
                    <option value="value2">Intermediate</option>
                    <option value="value3">Expert</option>
                </select>
            </div>
 <a href="{% url 'myapp:relationship' %}" class="link-button">Next</a>        </form>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/myapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<style>
    body{
        background-image: url("{% static 'images/backgroundimg.png' %}");
        background-position: center -60%;
    background-size: auto;
    background-repeat: no-repeat;
    }
    .container{
        position: center;
        top: 30px; 
        width: 290px;
        
       
    }
    
</style>
<body>
    
    <div class="container" >
        <h3 class="head"><center>Login</center></h3>
        <form method="POST" class="text_center" >
            {% csrf_token %}
        
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">Mobile or Email:</label>
            {{ form.username }}
            </div>
            <!-- <div class="form-group">
                <label for="{{ form.phone_number.id_for_label }}">Mobile</label>
                {{ form.phone_number }}
            </div> -->
            <div class="form-group">
                <label for="{{ form.password.id_for_label }}">Password</label>
            {{ form.password }}
            </div>
            <button type="submit" class="btn btn-dark btn-block">Log In</button><br><br>
           
        </form>
        <p><a href="{% url 'myapp:password_reset' %}" class="otp">Forgot password?</a></p>
        <p class="footer">Don't have an account? <a href="{% url 'myapp:signup' %}" class="link">Sign Up</a></p>
    </div>
    
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/myapp/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">

    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
</head>
<body>
<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <div id="error_div"></div>
                      <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                  <label class="small mb-1" for="id_email">Email</label>
                                    <input type="email" name="email"  class="form-control"
                                           autocomplete="email" maxlength="254" required id="id_email"
                                           placeholder="Enter email">
                                </div>
                            </div>
                        </div>
                            <div class="form-row">
                              <div class="col-md-10 offset-md-1">
                                <div class="form-group mt-0 mb-1">
                                    <button type="submit" class="col-md-12 btn btn-dark">Submit
                                    </button>
                                </div>
                             </div>
                           </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'myapp:signup' %}">Create A New Account</a><br><br>
                            <a href="{% url 'myapp:login' %}">Back To Login</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
</body>
</html>

myapp/templates/myapp/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'myapp:login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

myapp/templates/myapp/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}